name: Package Size Report
on:
  pull_request:
    branches: [ develop, master, next, next-major, beta, alpha ]
jobs:
  pkg-size-report:
    name: Package Size report
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package size report
        id: pkg-size-report
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          hide-files: '*.md'
          mode: 'head-only'
          display-size: brotli, uncompressed, gzip
